name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test:
    strategy:
      matrix:
        env:
          - { ROS_DISTRO: melodic, ROS_REPO: main }
          - { ROS_DISTRO: noetic, ROS_REPO: main }
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ros-industrial/industrial_ci@master
        env: ${{ matrix.env }}
